version: '3.10'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: creg

  web:
    command: bash -c "python3.10 manage.py makemigrations && python3.10 manage.py migrate && python3.10 manage.py runserver 0.0.0.0:8137"
    volumes:
      - .:/app
      - mediadata:/app/media
      - logdata:/app/logs
    ports:
      - "8137:8137"
    container_name: Creg
    image: creg
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=database_1.db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: DataBase
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always

  celery:
    command: bash -c "celery -A crag worker --loglevel=info"
    volumes:
      - .:/app
      - logdata:/app/logs
    depends_on:
      - db
    container_name: Celery
    image: creg
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    restart: always

  celerybeat:
    command: bash -c "celery -A crag beat -l info"
    volumes:
      - .:/app
      - logdata:/app/logs
    depends_on:
      - db
    container_name: Celery_Beat
    image: creg
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    restart: always

volumes:
  dbdata:
  migrationsdata:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/main/migrations
      o: bind
  mediadata:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/media
      o: bind
  logdata:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/logs
      o: bind
