from django.urls import path
from . import views

urlpatterns = [
    path('creation_tickets/', views.creation_tickets, name='creation_tickets'),
    path('open_tickets/', views.open_tickets, name='open_tickets'),
    path('send_test_mailing/', views.send_test_mailing, name='send_test_mailing'),
    path('clients/add/', views.add_client_and_card, name='add_client_and_card'),
    path('tech_account/add/<int:client_id>/', views.add_tech_account, name='add_tech_account'),
    path('tech_account/update/<int:account_id>/', views.update_tech_account, name='update_tech_account'),
    path('tech_account/delete/<int:account_id>/', views.delete_tech_account, name='delete_tech_account'),
    path('connect_info/add/<int:client_id>/', views.add_connect_info, name='add_connect_info'),
    path('connect_info/update/<int:connect_info_id>/', views.update_connect_info, name='update_connect_info'),
    path('connect_info/delete/<int:connect_info_id>/', views.delete_connect_info, name='delete_connect_info'),
    path('contact/add/<int:client_id>/', views.add_contact, name='add_contact'),
    path('contact/update/<int:contact_id>/', views.update_contact, name='update_contact'),
    path('contact/delete/<int:contact_id>/', views.delete_contact, name='delete_contact'),
    path('bm_server/add/<int:client_id>/', views.add_bm_server, name='add_bm_server'),
    path('bm_server/update/<int:server_id>/', views.update_bm_server, name='update_bm_server'),
    path('service_card/add/<int:client_id>/', views.add_service_card, name='add_service_card'),
    path('service_card/update/<int:service_card_id>/', views.update_service_card, name='update_service_card'),
    path('tech_info/add/<int:client_id>/', views.add_tech_information, name='add_tech_information'),
    path('tech_info/update/<int:info_id>/', views.update_tech_information, name='update_tech_information'),
    path('connection_info/add/<int:client_id>/', views.add_connection_info, name='add_connection_info'),
    path('connection_info/update/<int:connection_id>/', views.update_connection_info, name='update_connection_info'),
    path('tech_note/add/<int:client_id>/', views.add_tech_note, name='add_tech_note'),
    path('tech_note/update/<int:note_id>/', views.update_tech_note, name='update_tech_note'),
    path('upload_template/', views.upload_template, name='upload_template'),
    path('download_template/<str:template_name>/', views.download_template, name='download_template'),
    path('get_template_content/<str:template_name>/', views.get_template_content, name='get_template_content'),
]
