# Generated by Django 4.2 on 2023-04-23 16:45

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.CharField(default=main.models.generate_unique_id, max_length=255, verbose_name='Contacts')),
                ('tech_notes', models.CharField(default=main.models.generate_unique_id, max_length=255, verbose_name='Tech_notes')),
                ('connect_info', models.CharField(default=main.models.generate_unique_id, max_length=255, verbose_name='Connect_info')),
                ('rdp', models.CharField(default=main.models.generate_unique_id, max_length=255, verbose_name='RDP')),
                ('tech_account', models.CharField(default=main.models.generate_unique_id, max_length=255, verbose_name='Tech_account')),
                ('bm_servers', models.CharField(default=main.models.generate_unique_id, max_length=255, verbose_name='BM_servers')),
            ],
            options={
                'verbose_name_plural': 'Clients Cards',
                'db_table': 'clients_card',
            },
        ),
        migrations.CreateModel(
            name='ClientsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_index=True, max_length=255, verbose_name='Client_name')),
                ('contact_status', models.BooleanField(default=True, verbose_name='Contact Status')),
                ('service', models.CharField(default=main.models.generate_unique_id, max_length=255, verbose_name='Service')),
                ('technical_information', models.CharField(default=main.models.generate_unique_id, max_length=255, verbose_name='Technical_information')),
                ('integration', models.CharField(default=main.models.generate_unique_id, max_length=255, verbose_name='Integration')),
                ('documents', models.CharField(default=main.models.generate_unique_id, max_length=255, verbose_name='Documents')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Список клиентов',
                'db_table': 'clients_list',
            },
        ),
        migrations.CreateModel(
            name='ContactsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255, verbose_name='contact_name')),
                ('contact_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='contact_position')),
                ('contact_email', models.EmailField(max_length=255, verbose_name='contact_email')),
                ('notification_update', models.CharField(blank=True, max_length=255, null=True, verbose_name='notification_update')),
                ('contact_notes', models.TextField(blank=True, null=True, verbose_name='contact_notes')),
                ('client_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_cards', to='main.clientscard', verbose_name='Client Card')),
            ],
            options={
                'verbose_name_plural': 'Contacts Cards',
                'db_table': 'contacts_card',
            },
        ),
        migrations.AddField(
            model_name='clientscard',
            name='client_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clients_card', to='main.clientslist', verbose_name='Client_info'),
        ),
    ]
