# Generated by Django 4.2 on 2023-04-23 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientscard',
            options={'verbose_name': 'Карточка клиента', 'verbose_name_plural': 'Список карточек клиентов'},
        ),
        migrations.AlterModelOptions(
            name='contactscard',
            options={'verbose_name': 'Контакт клиента', 'verbose_name_plural': 'Список контактов клиентов'},
        ),
        migrations.CreateModel(
            name='СonnectInfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info_name', models.TextField(verbose_name='ФИО')),
                ('contact_info_account', models.TextField(verbose_name='Учетная_запись')),
                ('contact_info_password', models.TextField(verbose_name='Пароль')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_info_card', to='main.clientscard', verbose_name='Client Card')),
            ],
            options={
                'verbose_name': 'УЗ для подключения',
                'verbose_name_plural': 'Список УЗ для подключения',
                'db_table': 'connect_info_card',
            },
        ),
    ]
