# Generated by Django 4.2 on 2023-04-23 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clientscard_options_alter_contactscard_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='favicons/')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Картинки',
                'db_table': 'Favicon',
            },
        ),
        migrations.AlterField(
            model_name='contactscard',
            name='client_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_cards', to='main.clientscard', verbose_name='Client Card'),
        ),
    ]
