# Generated by Django 4.2 on 2023-05-07 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_favicon_alter_contactscard_client_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='СonnectInfoCard',
            new_name='ConnectInfoCard',
        ),
        migrations.CreateModel(
            name='BMServersCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bm_servers_circuit', models.TextField(verbose_name='Контур')),
                ('bm_servers_servers_name', models.TextField(verbose_name='Имя_сервера')),
                ('bm_servers_servers_adress', models.TextField(verbose_name='Адрес_сервера')),
                ('bm_servers_operation_system', models.TextField(null=True, verbose_name='Операционная_система')),
                ('bm_servers_url', models.TextField(null=True, verbose_name='URL')),
                ('bm_servers_role', models.TextField(verbose_name='Роль')),
                ('client_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bm_servers_cards', to='main.clientscard', verbose_name='Client Card')),
            ],
            options={
                'verbose_name': 'Сервер ВМ',
                'verbose_name_plural': 'Серверы ВМ',
                'db_table': 'bm_servers_card',
            },
        ),
    ]
