# Generated by Django 4.2 on 2023-05-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_сonnectinfocard_connectinfocard_bmserverscard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmserverscard',
            name='bm_servers_circuit',
            field=models.TextField(verbose_name='Circuit'),
        ),
        migrations.AlterField(
            model_name='bmserverscard',
            name='bm_servers_operation_system',
            field=models.TextField(null=True, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='bmserverscard',
            name='bm_servers_role',
            field=models.TextField(verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='bmserverscard',
            name='bm_servers_servers_adress',
            field=models.TextField(verbose_name='Server_ip_adress'),
        ),
        migrations.AlterField(
            model_name='bmserverscard',
            name='bm_servers_servers_name',
            field=models.TextField(verbose_name='Server_name'),
        ),
    ]
