# Generated by Django 4.2 on 2023-05-08 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bmserverscard_bm_servers_circuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmserverscard',
            name='bm_servers_circuit',
            field=models.CharField(max_length=100, verbose_name='Circuit'),
        ),
        migrations.AlterField(
            model_name='bmserverscard',
            name='bm_servers_operation_system',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='bmserverscard',
            name='bm_servers_role',
            field=models.CharField(max_length=100, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='bmserverscard',
            name='bm_servers_servers_adress',
            field=models.CharField(max_length=100, verbose_name='Server_ip_adress'),
        ),
        migrations.AlterField(
            model_name='bmserverscard',
            name='bm_servers_servers_name',
            field=models.CharField(max_length=100, verbose_name='Server_name'),
        ),
        migrations.AlterField(
            model_name='bmserverscard',
            name='bm_servers_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elasticsearch', models.BooleanField(blank=True, null=True, verbose_name='Elasticsearch')),
                ('ad', models.BooleanField(blank=True, null=True, verbose_name='AD')),
                ('adfs', models.BooleanField(blank=True, null=True, verbose_name='ADFS')),
                ('oauth_2', models.BooleanField(blank=True, null=True, verbose_name='OAuth_2.0')),
                ('module_translate', models.BooleanField(blank=True, null=True, verbose_name='Модуль_трансляции')),
                ('ms_oos', models.BooleanField(blank=True, null=True, verbose_name='MS OOS')),
                ('exchange', models.BooleanField(blank=True, null=True, verbose_name='Exchange')),
                ('office_365', models.BooleanField(blank=True, null=True, verbose_name='Office_365')),
                ('sfb', models.BooleanField(blank=True, null=True, verbose_name='Skype_For_Business')),
                ('zoom', models.BooleanField(blank=True, null=True, verbose_name='Zoom')),
                ('teams', models.BooleanField(blank=True, null=True, verbose_name='Teams')),
                ('smtp', models.BooleanField(blank=True, null=True, verbose_name='SMTP')),
                ('cryptopro_dss', models.BooleanField(blank=True, null=True, verbose_name='Cripto_DSS')),
                ('cryptopro_csp', models.BooleanField(blank=True, null=True, verbose_name='Cripto_CSP')),
                ('smpp', models.BooleanField(blank=True, null=True, verbose_name='SMPP')),
                ('limesurvey', models.BooleanField(blank=True, null=True, verbose_name='Анкетирование')),
                ('client_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration', to='main.clientscard', verbose_name='Client Card')),
            ],
            options={
                'verbose_name': 'Интеграция',
                'verbose_name_plural': 'Интеграции',
                'db_table': 'integration',
            },
        ),
    ]
