# Generated by Django 4.2 on 2023-05-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bmserverscard_bm_servers_circuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmserverscard',
            name='client_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bm_servers_card', to='main.clientscard', verbose_name='Client Card'),
        ),
        migrations.CreateModel(
            name='TechAccountCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info_disc', models.TextField(verbose_name='Описание')),
                ('contact_info_account', models.TextField(verbose_name='Учетная_запись')),
                ('contact_info_password', models.TextField(verbose_name='Пароль')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_account_card', to='main.clientscard', verbose_name='Client Card')),
            ],
            options={
                'verbose_name': 'Тех. УЗ клиента',
                'verbose_name_plural': 'Список тех. УЗ клиентов',
                'db_table': 'tech_account_card',
            },
        ),
    ]
