# Generated by Django 4.2 on 2023-05-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_client_id_techaccountcard_client_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectinfocard',
            old_name='client_id',
            new_name='client_card',
        ),
    ]
