# Generated by Django 4.2 on 2023-05-09 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_client_id_connectinfocard_client_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='uploaded_files/')),
                ('text', models.TextField(null=True)),
                ('client_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_info', to='main.clientscard')),
            ],
        ),
    ]
