# Generated by Django 4.2 on 2023-05-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_connectioninfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectioninfo',
            options={'verbose_name': 'Документы', 'verbose_name_plural': 'Документы по подключению к клиенту'},
        ),
        migrations.AlterField(
            model_name='techaccountcard',
            name='contact_info_account',
            field=models.CharField(max_length=255, verbose_name='Учетная_запись'),
        ),
        migrations.AlterField(
            model_name='techaccountcard',
            name='contact_info_disc',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='techaccountcard',
            name='contact_info_password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterModelTable(
            name='connectioninfo',
            table='connection_info',
        ),
        migrations.CreateModel(
            name='ServiseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_pack', models.CharField(max_length=255, verbose_name='service_pack')),
                ('manager', models.CharField(max_length=255, verbose_name='manager')),
                ('loyal', models.CharField(blank=True, max_length=255, null=True, verbose_name='loyal')),
                ('client_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servise_card', to='main.clientscard', verbose_name='Client Card')),
            ],
            options={
                'verbose_name': 'Обслуживание клиента',
                'verbose_name_plural': 'Список обслуживание клиентов',
                'db_table': 'servise_card',
            },
        ),
    ]
