# Generated by Django 4.2 on 2023-05-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_connectioninfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectinfocard',
            name='contact_info_account',
            field=models.CharField(max_length=255, verbose_name='Учетная_запись'),
        ),
        migrations.AlterField(
            model_name='connectinfocard',
            name='contact_info_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='connectinfocard',
            name='contact_info_password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
        migrations.CreateModel(
            name='TechInformationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_version', models.CharField(max_length=255, verbose_name='server_version')),
                ('update_date', models.DateField(max_length=255, verbose_name='update_date')),
                ('api', models.BooleanField(blank=True, null=True, verbose_name='api')),
                ('ipad', models.CharField(blank=True, max_length=255, null=True, verbose_name='ipad')),
                ('android', models.CharField(blank=True, max_length=255, null=True, verbose_name='android')),
                ('mdm', models.CharField(blank=True, max_length=255, null=True, verbose_name='mdm')),
                ('localizable_web', models.BooleanField(blank=True, null=True, verbose_name='localizable_web')),
                ('localizable_ios', models.BooleanField(blank=True, null=True, verbose_name='localizable_ios')),
                ('skins_web', models.BooleanField(blank=True, null=True, verbose_name='skins_web')),
                ('skins_ios', models.BooleanField(blank=True, null=True, verbose_name='skins_ios')),
                ('client_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_information', to='main.clientscard', verbose_name='Client Card')),
            ],
            options={
                'verbose_name': 'Техническая информация клиента',
                'verbose_name_plural': 'Список технической информации клиентов',
                'db_table': 'tech_information',
            },
        ),
    ]
