# Generated by Django 4.2 on 2023-05-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_connectinfocard_contact_info_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='ad',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='AD'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='adfs',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ADFS'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='cryptopro_csp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cripto_CSP'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='cryptopro_dss',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cripto_DSS'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='elasticsearch',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Elasticsearch'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='exchange',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='limesurvey',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Анкетирование'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='module_translate',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Модуль_трансляции'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='ms_oos',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='MS OOS'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='oauth_2',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='OAuth_2.0'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='office_365',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Office_365'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='sfb',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Skype_For_Business'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='smpp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='SMPP'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='smtp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='SMTP'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='teams',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Teams'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='zoom',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Zoom'),
        ),
        migrations.AlterField(
            model_name='techinformationcard',
            name='api',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='api'),
        ),
        migrations.AlterField(
            model_name='techinformationcard',
            name='localizable_ios',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='localizable_ios'),
        ),
        migrations.AlterField(
            model_name='techinformationcard',
            name='localizable_web',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='localizable_web'),
        ),
        migrations.AlterField(
            model_name='techinformationcard',
            name='skins_ios',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='skins_ios'),
        ),
        migrations.AlterField(
            model_name='techinformationcard',
            name='skins_web',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='skins_web'),
        ),
    ]
