# Generated by Django 4.2 on 2023-04-18 09:35

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_favicon_alter_client_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMInfoOnClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.TextField(db_index=True, verbose_name='Название клиента')),
                ('contact_status', models.BooleanField(verbose_name='Активность')),
                ('service', models.TextField(default=myapp.models.generate_unique_id, verbose_name='Обслуживание')),
                ('technical_information', models.TextField(default=myapp.models.generate_unique_id, verbose_name='Тех информация')),
                ('integration', models.TextField(default=myapp.models.generate_unique_id, verbose_name='Интеграции')),
                ('documents', models.TextField(default=myapp.models.generate_unique_id, verbose_name='Документы')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name_plural': 'BM Info on Clients',
                'db_table': 'bm_info_on_clients',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
