# Generated by Django 4.2 on 2023-04-18 13:15

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bminfoonclient_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsCard',
            fields=[
                ('client_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clients_card', serialize=False, to='myapp.bminfoonclient', verbose_name='Client_info')),
                ('contacts', models.CharField(default=myapp.models.generate_unique_id, max_length=255, verbose_name='Contacts')),
                ('tech_notes', models.CharField(default=myapp.models.generate_unique_id, max_length=255, verbose_name='Tech_notes')),
                ('connect_info', models.CharField(default=myapp.models.generate_unique_id, max_length=255, verbose_name='Connect_info')),
                ('rdp', models.CharField(default=myapp.models.generate_unique_id, max_length=255, verbose_name='RDP')),
                ('tech_account', models.CharField(default=myapp.models.generate_unique_id, max_length=255, verbose_name='Tech_account')),
                ('bm_servers', models.CharField(default=myapp.models.generate_unique_id, max_length=255, verbose_name='BM_servers')),
            ],
            options={
                'verbose_name_plural': 'Clients Cards',
                'db_table': 'clients_card',
            },
        ),
        migrations.AlterField(
            model_name='bminfoonclient',
            name='client_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Client_name'),
        ),
        migrations.AlterField(
            model_name='bminfoonclient',
            name='contact_status',
            field=models.BooleanField(default=True, verbose_name='Contact Status'),
        ),
        migrations.AlterField(
            model_name='bminfoonclient',
            name='documents',
            field=models.CharField(default=myapp.models.generate_unique_id, max_length=255, verbose_name='Documents'),
        ),
        migrations.AlterField(
            model_name='bminfoonclient',
            name='integration',
            field=models.CharField(default=myapp.models.generate_unique_id, max_length=255, verbose_name='Integration'),
        ),
        migrations.AlterField(
            model_name='bminfoonclient',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='bminfoonclient',
            name='service',
            field=models.CharField(default=myapp.models.generate_unique_id, max_length=255, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='bminfoonclient',
            name='technical_information',
            field=models.CharField(default=myapp.models.generate_unique_id, max_length=255, verbose_name='Technical_information'),
        ),
    ]
