apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mediadata
  namespace: creg
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: "nfs-client"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-backup
  namespace: creg
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "nfs-client"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logdata
  namespace: creg
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: "nfs-client"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-templates
  namespace: creg
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: "nfs-client"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-migrations
  namespace: creg
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "nfs-client"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dbdata
  namespace: creg
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "nfs-client"
